POST http://localhost:3003/api/lists/6481e9718d8eab20089e651f/items
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJ0d29AbWFpbC5jb20iLCJpZCI6IjY0ODFlOTEyOGQ4ZWFiMjAwODllNjUxNCIsImlhdCI6MTY4NjI0NDk3Nn0.1tg9uONBux8by0W8KPCuJI410Fs4xRu5K50Aji01jbQ

{
  "content": "Item 5"
}