POST http://localhost:3003/api/lists/648a9e9967fec9c12c057ac5/items
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJ0d29AbWFpbC5jb20iLCJpZCI6IjY0ODgyZDkyNmQxYTg1NTVhM2RlZGVlMCIsImlhdCI6MTY4NjgwOTE0Nn0.vQ9xXlnBY_I5h-zWRcFEYInmic85h4k9zDllpfMDoHQ

{
  "content": {"name": "Item 4", "amount": 4, "unit": "piece"}
}