DELETE http://localhost:3003/api/users/649e895dfd83c5a9890d413d
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRlbGV0ZXRoaXNAbWFpbC5jb20iLCJpZCI6IjY0OWU4OTVkZmQ4M2M1YTk4OTBkNDEzZCIsImlhdCI6MTY4ODExMTU0N30.ehKeeiqPI_kURnOHWfwkArzR6IfwDAyVo6kKTMH-fX4
