DELETE http://localhost:3003/api/users/647d84c76cdd9ff422ea4735/lists/647d87d9f3a6575e971d6912
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJuYW1lIiwiaWQiOiI2NDdkODRjNzZjZGQ5ZmY0MjJlYTQ3MzUiLCJpYXQiOjE2ODU5NDkyNDl9.HYgljsW3kAKQYq-DPXw6Ys6ksr8BPTIQlR15sBjpSSc
