DELETE http://localhost:3003/api/lists/6481b7de89447e662248506c/items/6481b7de89447e662248506a
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAbWFpbC5jb20iLCJpZCI6IjY0N2YzMGRmZWQ5OTc1ZTNiZDVkYWJjZCIsImlhdCI6MTY4NjY0MzY0MH0.Tt8fyw6tQjCkc-Wo6F-1YXu9aQEEqwNxq6momIfePnY
