PUT http://localhost:3003/api/users/change-password
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImthaS5qdWthcmFpbmVuQGdtYWlsLmNvbSIsImlkIjoiNjRiOGY0NTQ5YTJjMjE4OTFlOTQwNTBmIiwiaWF0IjoxNjg5ODQ1NzAzfQ.Zzv_h9X_jVCQg4ndrecJI5DqV4GphMQ1fASv_mHZd2k

{
  "oldPassword": "bPfup7JhfY",
  "newPassword": "qweqweqwe"
}